CREATE TABLE Accounts(
    ID INT NOT NULL PRIMARY KEY IDENTITY,
	Nick NVARCHAR(31) NOT NULL,
	FirstName NVARCHAR(31) NOT NULL,
	LastName NVARCHAR(31) NOT NULL,
	PasswordString NVARCHAR(63) NOT NULL,
	PathToPhoto NVARCHAR(31) NOT NULL,
	);