CREATE TABLE CharacterSkins(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	Skin1 INT NOT NULL,
	Skin2 INT NOT NULL,
	Skin3 INT NOT NULL,
	Skin4 INT NOT NULL,
	Skin5 INT NOT NULL,
	Skin6 INT NOT NULL,
	PlayerID INT FOREIGN KEY(PlayerID) REFERENCES AvailablePoints(ID) NOT NULL
	);
	
ALTER TABLE CharacterSkins
ADD WastedPoints INT NOT NULL DEFAULT(0)
GO