// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiłoszGajowczykLab7.Models;

namespace MiłoszGajowczykLab7.Migrations
{
    [DbContext(typeof(SkiJumpingContext))]
    [Migration("20190605182228_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiłoszGajowczykLab7.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<float>("Record");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("MiłoszGajowczykLab7.Models.Jumper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay");

                    b.Property<int>("CountryId");

                    b.Property<string>("FirstName");

                    b.Property<float>("Height");

                    b.Property<string>("LastName");

                    b.Property<float>("PersonalBest");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Jumpers");
                });

            modelBuilder.Entity("MiłoszGajowczykLab7.Models.Jumper", b =>
                {
                    b.HasOne("MiłoszGajowczykLab7.Models.Country", "Country")
                        .WithMany("Jumpers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
